---
# This playbook sets up a server for the NCDR reference library project

- name: Things you want on servers generally
  sudo: yes
  user: ubuntu
  hosts: webserver
  gather_facts: no
  roles:
    - server

- name: Make the server capable of running a standard Django deployment
  sudo: yes
  user: ubuntu
  hosts: webserver
  roles:
    - django

- name: Set up our project
  sudo: yes
  user: ubuntu
  hosts: webserver
  roles:
    - ncdr

# Backups
