---
# set up the NCDR project itself

- name: Setup the Git repo
  git: repo={{ git_repo }}
       version={{ git_branch }}
       dest={{ project_path }}
       accept_hostkey=yes
       force=yes

- name: Delete all .pyc files
  command: find . -name '*.pyc' -delete
  args:
    chdir: "{{ project_path }}"
  tags: git
  changed_when: False

- name: Creates log dir
  file:
    path: "{{ log_dir }}"
    state: directory

# otherwise it complains silently and
# blows up the world
- name: Creates gunicorn log
  file:
    path: "{{ log_dir }}/gunicorn.log"
    state: touch

- name: Create configs
  template:
    src: "templates/{{ item }}.jinja2"
    dest: "{{ project_path }}/deployment/config/{{ item }}"
    mode: 0744
    owner: ubuntu
  with_items:
    - circus.ini
    - gunicorn.conf
    - gunicorn_conf.py
    - nginx_site.conf

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}
  executable: pip3

- name: Create local settings
  template:
    src: "templates/local_settings.py.jinja2"
    dest: "{{ project_path }}/ncdr_reference/local_settings.py"
    mode: 0744
    owner: ubuntu

- name: Run Django database migrations
  args:
    chdir: "{{ project_path}}"
  command: "{{ virtualenv_path }}/bin/python manage.py migrate"

- name: Run Django collectstatic
  args:
    chdir: "{{ project_path}}"
  command: "{{ virtualenv_path }}/bin/python manage.py collectstatic --noinput"

- name: Run Django initial_load
  args:
    chdir: "{{ project_path}}"
  command: "{{ virtualenv_path }}/bin/python manage.py initial_load"

- name: Remove old nginx default
  become: true
  file:
    state: absent
    path: "/etc/nginx/sites-available/default"

- name: Symlink nginx
  become: true
  file:
    src: "{{ project_path }}/deployment/config/nginx_site.conf"
    dest: "/etc/nginx/sites-available/default"
    owner: root
    group: root
    state: link

- name: Restart nginx
  become: true
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: Kill gunicorn
  sudo: yes
  command: "pkill gunicorn"
  ignore_errors: True

# change this to restart the controller
- name: Kill circus
  sudo: yes
  command: "pkill circus"
  ignore_errors: True

- name: Start app
  args:
    chdir: "{{ project_path }}"
  command: "circusd --daemon deployment/config/circus.ini"
